### ISSUE TITLE
track slick

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#12] opened 2014-03-05 05:34 UTC
currently at "slick/slick.git#pull/686/head"

**Comment by SethTisue** [comment] 2015-10-09 21:20
fixed by https://github.com/scala/community-builds/pull/137 for the 2.12 build

**Comment by SethTisue** [comment] 2015-10-10 15:11
@szeiger on 2.11 I get the following. any idea what this is about?

```
[slick] Processing subproject: osgitests
[slick] All Dependencies for subproject osgitests:
[slick]    org.scala-lang:scala-compiler:2.11.8-dbuildx4b3cb89f76c5caa3cc7ada3b5ebb90c5961d2b8e:scala-tool->default,optional(default)
[slick]    org.scala-lang:scala-library:2.11.8-dbuildx4b3cb89f76c5caa3cc7ada3b5ebb90c5961d2b8e:scala-tool->default,optional(default)
[slick]    com.typesafe.slick:slick:3.2.0-dbuildxe2ffc32ea14aa8a82771db64d1264f39f7b0e462:test
[slick]    org.scala-lang:scala-library:2.11.8-dbuildx4b3cb89f76c5caa3cc7ada3b5ebb90c5961d2b8e
[slick]    com.h2database:h2:1.4.187:test
[slick]    ch.qos.logback:logback-classic:1.1.3:test
[slick]    junit:junit-dep:4.10:test
[slick]    com.novocode:junit-interface:0.11:test
[slick]    org.reactivestreams:reactive-streams:1.0.0:test
[slick]    org.ops4j.pax.exam:pax-exam-container-native:4.6.0:test
[slick]    org.ops4j.pax.exam:pax-exam-junit4:4.6.0:test
[slick]    org.ops4j.pax.exam:pax-exam-link-assembly:4.6.0:test
[slick]    org.ops4j.pax.url:pax-url-aether:1.6.0:test
[slick]    org.ops4j.pax.swissbox:pax-swissbox-framework:1.5.1:test
[slick]    org.apache.felix:org.apache.felix.framework:4.6.1:test
[slick] Running build: osgitests
[slick] Testing: osgitests
[slick] [info] Updating {file:/home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.1/project-builds/slick-e2ffc32ea14aa8a82771db64d1264f39f7b0e462/}osgitests...
[slick] [warn] bnd: Split package, multiple jars provide the same package:slick/util
[slick] [warn] Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
[slick] [warn] Package found in   [Jar:classes, Jar:macro-classes]
[slick] [warn] Class path         [Jar:classes, Jar:macro-classes, Jar:scala-library-2.11.8-dbuildx4b3cb89f76c5caa3cc7ada3b5ebb90c5961d2b8e, Jar:slf4j-api-1.7.10, Jar:config-1.2.1, Jar:reactive-streams-1.0.0, Jar:scala-compiler-2.11.8-dbuildx4b3cb89f76c5caa3cc7ada3b5ebb90c5961d2b8e, Jar:scala-reflect-2.11.8-dbuildx4b3cb89f76c5caa3cc7ada3b5ebb90c5961d2b8e, Jar:scala-xml-1.0.6-dbuildxcacf386c23eb6cc5d5d2573aa1929fa2b75c0206, Jar:scala-parser-combinators-1.1.0-dbuildxdea5f979a334d6566b075c99de2307b73f0f71f8]
[slick] [warn] bnd: Unused Export-Package instructions: [scala.slick.*] 
[slick] [info] Done updating.
[slick] [info] Compiling 2 Scala sources to /home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.1/project-builds/slick-e2ffc32ea14aa8a82771db64d1264f39f7b0e462/osgi-tests/target/scala-2.11/test-classes...
[slick] [error] Uncaught exception when running slick.osgi.test.BasicTest: java.lang.UnsupportedClassVersionError: org/ops4j/pax/exam/junit/PaxExam : Unsupported major.minor version 51.0
[slick] sbt.ForkMain$ForkError: java.lang.UnsupportedClassVersionError: org/ops4j/pax/exam/junit/PaxExam : Unsupported major.minor version 51.0
[slick]     at java.lang.ClassLoader.defineClass1(Native Method)
[slick]     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
[slick]     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
[slick]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[slick]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[slick]     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[slick]     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[slick]     at java.security.AccessController.doPrivileged(Native Method)
[slick]     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[slick]     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[slick]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[slick]     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[slick]     at java.lang.Class.forName0(Native Method)
[slick]     at java.lang.Class.forName(Class.java:249)
[slick]     at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
[slick]     at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
[slick]     at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
[slick]     at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
[slick]     at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:351)
[slick]     at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:280)
[slick]     at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:222)
[slick]     at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
[slick]     at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
[slick]     at java.lang.Class.initAnnotationsIfNecessary(Class.java:3079)
[slick]     at java.lang.Class.getAnnotation(Class.java:3038)
[slick]     at com.novocode.junit.JUnitRunner.shouldRun(JUnitRunner.java:169)
[slick]     at com.novocode.junit.JUnitRunner.access$400(JUnitRunner.java:20)
[slick]     at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:123)
[slick]     at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[slick]     at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[slick]     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[slick]     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[slick]     at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
[slick]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
[slick]     at java.lang.Thread.run(Thread.java:662)
[slick] [error] Error: Total 1, Failed 0, Errors 1, Passed 0
[slick] [error] Error during tests:
[slick] [error]     slick.osgi.test.BasicTest
[slick] [error] (osgitests/test:test) sbt.TestsFailedException: Tests unsuccessful
[slick:error] Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.1/project-builds/slick-e2ffc32ea14aa8a82771db64d1264f39f7b0e462/,osgitests)),Select(ConfigKey(test)),Global,Global),test)), tpe=Error, msg=None, causes=List(), directCause=Some(sbt.TestsFailedException: Tests unsuccessful))
[slick:error]   at sbt.Incomplete.copy(Incomplete.scala:17)
[slick:error]   at sbt.EvaluateTask$$anonfun$taskToKey$1.apply(EvaluateTask.scala:400)
[slick:error]   at sbt.EvaluateTask$$anonfun$taskToKey$1.apply(EvaluateTask.scala:399)
[slick:error]   at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[slick:error]   at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[slick:error]   at sbt.Incomplete$$anonfun$sbt$Incomplete$$visit$1$1.apply(Incomplete.scala:32)
[slick:error]   at sbt.Incomplete$$anonfun$sbt$Incomplete$$visit$1$1.apply(Incomplete.scala:32)
[slick:error]   at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
[slick:error]   at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
[slick:error]   at sbt.Incomplete$.sbt$Incomplete$$visit$1(Incomplete.scala:32)
[slick:error]   at sbt.Incomplete$.transform(Incomplete.scala:36)
[slick:error]   at sbt.Incomplete$.transformBU(Incomplete.scala:26)
[slick:error]   at sbt.EvaluateTask$$anonfun$transformInc$1.apply(EvaluateTask.scala:398)
[slick:error]   at sbt.EvaluateTask$$anonfun$transformInc$1.apply(EvaluateTask.scala:398)
[slick:error]   at scala.util.Either$LeftProjection.map(Either.scala:377)
[slick:error]   at sbt.EvaluateTask$.transformInc(EvaluateTask.scala:398)
[slick:error]   at sbt.EvaluateTask$.run$1(EvaluateTask.scala:364)
[slick:error]   at sbt.EvaluateTask$.runTask(EvaluateTask.scala:378)
[slick:error]   at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:279)
[slick:error]   at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:279)
[slick:error]   at scala.Option$WithFilter.map(Option.scala:206)
[slick:error]   at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:279)
[slick:error]   at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:278)
[slick:error]   at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:314)
[slick:error]   at sbt.EvaluateTask$.apply(EvaluateTask.scala:278)
[slick:error]   at sbt.EvaluateTask$.apply(EvaluateTask.scala:276)
[slick:error]   at sbt.Extracted.runTask(Extracted.scala:44)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$.com$typesafe$dbuild$DistributedRunner$$buildTestPublish$1(DistributedRunner.scala:596)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$19.apply(DistributedRunner.scala:616)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$19.apply(DistributedRunner.scala:616)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$runAggregate$1.apply(DistributedRunner.scala:70)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$runAggregate$1.apply(DistributedRunner.scala:67)
[slick:error]   at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
[slick:error]   at scala.collection.immutable.List.foldLeft(List.scala:84)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$.com$typesafe$dbuild$DistributedRunner$$runAggregate(DistributedRunner.scala:67)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$14.apply(DistributedRunner.scala:574)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$14.apply(DistributedRunner.scala:574)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$.buildStuff(DistributedRunner.scala:616)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$generateArtifacts$1.apply(DistributedRunner.scala:745)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$generateArtifacts$1.apply(DistributedRunner.scala:745)
[slick:error]   at com.typesafe.dbuild.StateHelpers$.saveLastMsg(StateHelpers.scala:35)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$.generateArtifacts(DistributedRunner.scala:745)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$buildIt$1.apply(DistributedRunner.scala:749)
[slick:error]   at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$buildIt$1.apply(DistributedRunner.scala:749)
[slick:error]   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
[slick:error]   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
[slick:error]   at sbt.Command$.process(Command.scala:93)
[slick:error]   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[slick:error]   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[slick:error]   at sbt.State$$anon$1.process(State.scala:184)
[slick:error]   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[slick:error]   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[slick:error]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[slick:error]   at sbt.MainLoop$.next(MainLoop.scala:98)
[slick:error]   at sbt.MainLoop$.run(MainLoop.scala:91)
[slick:error]   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
[slick:error]   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
[slick:error]   at sbt.Using.apply(Using.scala:24)
[slick:error]   at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
[slick:error]   at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
[slick:error]   at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
[slick:error]   at sbt.MainLoop$.runLogged(MainLoop.scala:24)
[slick:error]   at sbt.StandardMain$.runManaged(Main.scala:53)
[slick:error]   at sbt.xMain.run(Main.scala:28)
[slick:error]   at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
[slick:error]   at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
[slick:error]   at xsbt.boot.Launch$.run(Launch.scala:57)
[slick:error]   at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
[slick:error]   at xsbt.boot.Launch$.launch(Launch.scala:65)
[slick:error]   at xsbt.boot.Launch$.apply(Launch.scala:16)
[slick:error]   at xsbt.boot.Boot$.runImpl(Boot.scala:32)
[slick:error]   at xsbt.boot.Boot$.main(Boot.scala:21)
[slick:error]   at xsbt.boot.Boot.main(Boot.scala)
[slick:error] Caused by: sbt.TestsFailedException: Tests unsuccessful
[slick:error]   at sbt.TestResultLogger$Defaults$Main.run(TestResultLogger.scala:95)
[slick:error]   at sbt.Defaults$$anonfun$testTasks$5.apply(Defaults.scala:421)
[slick:error]   at sbt.Defaults$$anonfun$testTasks$5.apply(Defaults.scala:418)
[slick:error]   at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[slick:error]   at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[slick:error]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[slick:error]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[slick:error]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[slick:error]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[slick:error]   at sbt.Execute.work(Execute.scala:235)
[slick:error]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[slick:error]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[slick:error]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[slick:error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[slick:error]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[slick:error]   at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[slick:error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
[slick:error]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[slick:error]   at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[slick:error]   at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
[slick:error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
[slick:error]   at java.lang.Thread.run(Thread.java:662)
[slick:error] java.lang.RuntimeException: Tests unsuccessful
[slick:error]   at scala.sys.package$.error(package.scala:27)
[slick:error]   at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[slick:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[slick:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[slick:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[slick:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[slick:error]   at sbt.IO$.withTemporaryFile(IO.scala:311)
[slick:error]   at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[slick:error]   at distributed.support.sbt.SbtBuilder$.buildSbtProject(SbtBuildRunner.scala:84)
[slick:error]   at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:68)
[slick:error]   at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:18)
```

this is from https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/85/console

looks like the same thing when building on JDK8 too: https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/54/consoleFull

**Comment by SethTisue** [comment] 2015-10-21 14:59
@szeiger ping

**Comment by szeiger** [comment] 2015-10-21 15:29
Slick 3.2 will require Java 8, so I upgraded the build to Java 8 and also upgraded the OSGi test environment because the old version was broken on Java 8. That said, I can still build it and successfully run the OSGi tests locally under Java 7.

The osgitests project is the only one with `fork in Test := true`. Is the correct `java` command on the path for the build? Maybe the one on the path is Java 6 and only dbuild is run with Java 7 or 8? This could explain why the forked test fails due to a version 51 (Java 7) class file.

The error on JDK8 seems to be a different one:

```
[slick] [error] Test slick.osgi.test.BasicTest.testConfig failed: org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: org.reactivestreams.reactive-streams:1.0.0.release, took 0.203 sec
[slick] [error]     at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1311)
[slick] [error]     at org.apache.felix.framework.BundleImpl.this(BundleImpl.java:113)
[slick] [error]     at org.apache.felix.framework.Felix.installBundle(Felix.java:2976)
[slick] [error]     at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
[slick] [error]     at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:140)
[slick] [error]     at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:308)
[slick] [error]     at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:177)
[slick] [error]     at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)
[slick] [error]     at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:267)
[slick] [error]     ...
```

I cannot reproduce the actual test failure locally, either, but I can reproduce the duplicate entry for reactive-streams:

```
> show osgitests/osgiBundleFiles
[warn] bnd: Split package, multiple jars provide the same package:slick/util
[warn] Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
[warn] Package found in   [Jar:classes, Jar:macro-classes]
[warn] Class path         [Jar:classes, Jar:macro-classes, Jar:scala-library-2.11.7, Jar:slf4j-api-1.7.10, Jar:config-1.2.1, Jar:reactive-streams-1.0.0, Jar:scala-compiler-2.11.7, Jar:scala-reflect-2.11.7, Jar:scala-xml_2.11-1.0.4, Jar:scala-parser-combinators_2.11-1.0.4]
[warn] bnd: Unused Export-Package instructions: [scala.slick.*]
[warn] bnd: No translation found for macro: range;[==,=+)
[info] List(/Users/szeiger/code/slick/slick/target/scala-2.11/slick_2.11-3.2.0-SNAPSHOT.jar, /Users/szeiger/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar, /Users/szeiger/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.10.jar, /Users/szeiger/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar, /Users/szeiger/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar, /Users/szeiger/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.7.jar, /Users/szeiger/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.7.jar, /Users/szeiger/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.4.jar, /Users/szeiger/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar, /Users/szeiger/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar, /Users/szeiger/.ivy2/cache/com.h2database/h2/jars/h2-1.4.187.jar, /Users/szeiger/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar, /Users/szeiger/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar)
```

I'll try to fix this and submit a PR to Slick.

(There's yet another OSGi test related error in the RP dbuild which we couldn't figure out, so we ended up disabling the OSGi tests there.)

**Comment by SethTisue** [comment] 2015-10-21 15:53
thanks, this is very helpful.

ok, it sounds like the OSGi tests are somewhat fragile, at least in a dbuild context, and I'm in shortcut-taking mode on community build stuff so I can devote more attention to other things, so I think I'll just disable the OSGi tests on any branches where they're failing.

since master now expects Java 8, I'll change the 2.11.x/jdk6 to use the 3.1 branch instead of master.

**Comment by szeiger** [comment] 2015-10-21 16:24
The problem on JDK8 with Slick master should now be fixed/

**Comment by SethTisue** [comment] 2015-10-22 19:07
progress: https://github.com/scala/community-builds/pull/138

**Closed** 2015-10-22 19:59 UTC
