### ISSUE TITLE
Cats tests not being compiled

### ISSUE THREAD

**Issue by milessabin** [scala/community-builds#409] opened 2016-11-28 10:24 UTC
I noticed this when running a community build with `-Xexperimental` enabled. `-Xexperimental` enables `-Ypartial-unification` which should cause the compilation of the Cats tests to fail. There's no failure, so it appears that the tests are not being compiled.

**Comment by dwijnand** [comment] 2016-11-28 10:28
Both the [2.12.0](https://github.com/scala/community-builds/blob/618eaed3a32e82bec767b6e8eb6e8ccee5cf1fd4/community.dbuild#L423) and [2.12.x](https://github.com/scala/community-builds/blob/22b9e1547380856eb32174d404558613aae78982/community.dbuild#L413) branches only build the `coreJVM` and `macrosJVM` projects, with a comment saying "this is only some of Cats. we should try and add more".

**Comment by SethTisue** [comment] 2016-11-28 15:23
duplicate of #363

**Closed as completed by SethTisue** 2016-11-28 15:23 UTC
