### ISSUE TITLE
"Unsupported class file major version 56" error in JDK 12 build

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/community-builds#864] opened 2019-02-16 13:11 UTC
```
[jsoniter-scala] [error] ## Exception when compiling 5 sources to /home/jenkins/workspace/scala-2.12.x-jdk12-integrate-community-build/target-0.9.16/project-builds/jsoniter-scala-f34d7e137bb3b09515c1eb076c6f60023632077e/jsoniter-scala-core/target/scala-2.12/classes
[jsoniter-scala] [error] Unsupported class file major version 56
```
Here is a list of projects that are immediately affected by this kind of error [in the latest build](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk12-integrate-community-build/16/consoleFull):
- breeze
- curryhoward
- log4s
- jsoniter-scala
- scala-async
- scala-partest
- scalaz
- utest

**Comment by SethTisue** [comment] 2019-02-20 02:13
thanks for the report. I'm not sure what the cause is. I plan to investigate, but I have some other, more pressing community build stuff to attend to first. I've assigned myself the issue so I don't forget.

**Comment by SethTisue** [comment] 2019-02-21 01:19
reproducible outside of dbuild, in e.g. scala-async with just `compile`

the problem is also present with `++2.13.0-M5` but goes away with `++2.13.0-pre-481a78b!`. that and the error message strongly suggest that fixing this requires moving to ASM 7, as was done for the 2.13.x series by https://github.com/scala/scala/pull/7384

an existing ticket in this general area: https://github.com/scala/bug/issues/11372

**Comment by SethTisue** [comment] 2019-02-22 01:06
hopefully scala/scala#7780 will do the trick

**Comment by SethTisue** [comment] 2019-02-24 01:26
it seems very likely that scala/bug#11372 is the only bug here

**Closed as completed by SethTisue** 2019-02-24 01:26 UTC
